services:
  usuarios-service:
    build:
      context: ./backend/usuarios
      dockerfile: Dockerfile
    container_name: usuarios-service
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - abc-network

  pedidos-service:
    build:
      context: ./backend/pedidos
      dockerfile: Dockerfile
    container_name: pedidos-service
    ports:
      - "8082:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - abc-network

  pagos-service:
    build:
      context: ./backend/pagos
      dockerfile: Dockerfile
    container_name: pagos-service
    ports:
      - "8083:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - abc-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: abc-frontend
    ports:
      - "4200:4000"
    environment:
      PORT: 4000
      NG_ALLOWED_HOSTS: localhost,127.0.0.1
    networks:
      - abc-network
      
  mongodb:
    image: mongo:8
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: abc_mvp_db
    networks:
      - abc-network

networks:
  abc-network:
    driver: bridge
